name: ci

on:
  push:
    branches:
      - master
    # tags:
    #   - v1.**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.4.0

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Run go vet
      run: go vet ./...

    - name: Run tests
      run: go test -race -vet=off -v -cover ./...