name: lint

on:
  push:
    branches:
      - master
    # tags:
    #   - v1.**

jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.18, 1.19, 1.20]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.4.0